environment:
  nodejs_version: "0.10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run gulp build
  - npm run gulp cucumber
  - npm run gulp jasmine

build: off
