// Generated by CoffeeScript 1.8.0
(function() {
  var $, App;

  App = typeof exports !== "undefined" && exports !== null ? exports : window;

  $ = jQuery;


  /*
   * @module coffeeMind
   */

  App.coffeeMind = (function() {
    var aboutPath, boardPath, displayCanvasPath, gamePath, gameScreenPath, getLoadProgress, highscoreSreen, imageProto, imagesPath, inputPath, installScreenPath, mainMenuPath, numLoaded, numPreload, rect, screenSplashPath, settings, srcPath, storage, storageCookies;
    srcPath = App.srcPath;
    storage = "loader!" + srcPath + "scripts/storage.js";
    storageCookies = "loader!" + srcPath + "scripts/storage.cookie.js";
    screenSplashPath = "loader!" + srcPath + "scripts/screen.splash.js";
    installScreenPath = "loader!" + srcPath + "scripts/screen.install.js";
    gamePath = "loader!" + srcPath + "scripts/game.js";
    boardPath = "loader!" + srcPath + "scripts/board.js";
    inputPath = "loader!" + srcPath + "scripts/input.js";
    mainMenuPath = "loader!" + srcPath + "scripts/screen.main-menu.js";
    displayCanvasPath = "loader!" + srcPath + "scripts/display.canvas.js";
    gameScreenPath = "loader!" + srcPath + "scripts/screen.game.js";
    aboutPath = "loader!" + srcPath + "scripts/screen.about.js";
    highscoreSreen = "loader!" + srcPath + "scripts/screen.highscore.js";
    settings = {
      rows: 10,
      cols: 4,
      baseScore: 100,
      numColors: 4,
      availableColours: 6,
      allowMultipleColors: false,
      imageSize: void 0,
      baseLevelTimer: 120000,
      baseLevelScore: 1500,
      baseLevelExp: 1.05,
      controls: {
        KEY_UP: "nextColor",
        KEY_LEFT: "moveLeft",
        KEY_DOWN: "previousColor",
        KEY_RIGHT: "moveRight",
        KEY_ENTER: "checkColors",
        KEY_ESCAPE: "resetBoard",
        KEY_SPACE: "getSolution",
        CLICK: "nextColor",
        TOUCH: "nextColor"
      },
      images: {},
      srcPath: srcPath
    };
    App.settings = settings;
    Modernizr.addTest("standalone", function() {
      var test;
      test = App.navigator.standalone !== false;
      console.log("Standalone test: " + test);
      return test;
    });
    yepnope.addPrefix("preload", function(resource) {
      resource.noexec = true;
      console.log("preload: " + resource.url);
      return resource;
    });
    numPreload = 0;
    numLoaded = 0;
    yepnope.addPrefix("loader", function(resource) {
      var image, isImage;
      console.log("Loading: " + resource.url);
      isImage = /.+\.(jpg|png|gif)$/i.test(resource.url);
      resource.noexec = isImage;
      numPreload++;
      resource.autoCallback = function(e) {};
      console.log("Finished loading: " + resource.url);
      numLoaded++;
      if (isImage) {
        image = new Image();
        image.src = resource.url;
        settings.images[resource.url] = image;
      }
      return resource;
    });
    imageProto = document.getElementById("image-proto");
    rect = imageProto.getBoundingClientRect();
    console.log("proto-image bounding width (px):" + rect.width);
    settings.imageSize = rect.width;
    getLoadProgress = function() {
      if (numPreload > 0) {
        return numLoaded / numPreload;
      } else {
        return 0;
      }
    };
    console.log("started loading stage 1");
    Modernizr.load({
      test: Modernizr.localstorage,
      yep: storage,
      nope: storageCookies
    });
    Modernizr.load({
      load: [gamePath],
      test: Modernizr.standalone,
      yep: screenSplashPath,
      nope: installScreenPath,
      complete: function() {
        App.coffeeMind.game.setup(settings, $);
        if (Modernizr.standalone) {
          App.coffeeMind.game.showScreen("splash-screen", getLoadProgress);
          console.log("showScreen: splash-screen");
        } else {
          App.game.showScreen("install-screen");
          console.log("showScreen: install-screen");
        }
        return console.log("stage 1 loaded");
      }
    });
    console.log("started loading stage 2");
    imagesPath = "loader!" + srcPath + "images/forms_" + settings.imageSize + ".png";
    if (Modernizr.standalone) {
      return Modernizr.load({
        load: [boardPath, inputPath, mainMenuPath, displayCanvasPath, gameScreenPath, imagesPath, aboutPath, highscoreSreen],
        complete: function() {
          return console.log("stage 2 loaded");
        }
      });
    }
  })();

}).call(this);

//# sourceMappingURL=loader.js.map
