// Generated by CoffeeScript 1.8.0
(function() {
  var App;

  App = typeof exports !== "undefined" && exports !== null ? exports : window;

  App.coffeeMind = App.coffeeMind || {};

  App.coffeeMind.screens = App.coffeeMind.screens || {};

  App.coffeeMind.screens["about"] = (function() {
    var game, run, setup, _$;
    game = {};
    _$ = $;
    setup = function($) {
      var _game;
      _$ = $;
      _game = App.coffeeMind.game;
      return null;
    };

    /*
     * @method run
     * @param {method} getLoadProgress callback
     */
    run = function($) {
      setup($);
      return null;
    };
    return {
      run: run
    };
  })();

}).call(this);

//# sourceMappingURL=screen.about.js.map
