// Generated by CoffeeScript 1.8.0
(function() {
  var App;

  App = typeof exports !== "undefined" && exports !== null ? exports : window;

  App.coffeeMind = App.coffeeMind || {};

  App.coffeeMind.screens = App.coffeeMind.screens || {};

  App.coffeeMind.screens["splash-screen"] = (function() {
    var game, run, setup, _$;
    game = {};
    _$ = $;

    /*
     * @method setup
     * @param {method} getLoadProgress callback
     */
    setup = function($, getLoadProgress) {
      var $src, checkProgress;
      _$ = $;
      game = App.coffeeMind.game;
      $src = _$("#splash-screen");
      checkProgress = function() {
        var p;
        p = getLoadProgress() * 100;
        _$(".indicator", $src).css("width", p + "%");
        if (p === 100) {
          _$(".continue", $src).css("display", "block");
          return _$("#splash-screen").bind('click', function() {
            game.showScreen('main-menu');
            return null;
          });
        } else {
          return setTimeout(checkProgress, 30);
        }
      };
      checkProgress();
      return null;
    };

    /*
     * @method run
     * @param {method} getLoadProgress callback
     */
    run = function($, getLoadProgress) {
      setup($, getLoadProgress);
      return null;
    };
    return {
      run: run
    };
  })();

}).call(this);

//# sourceMappingURL=screen.splash.js.map
