// Generated by CoffeeScript 1.8.0
(function() {
  var App;

  App = typeof exports !== "undefined" && exports !== null ? exports : window;

  App.coffeeMind = App.coffeeMind || {};


  /*
   * @method App.coffeeMind.storage
   * @return {Object} API objects
   */

  App.coffeeMind.storage = (function() {
    var cookieKey, get, load, set;
    cookieKey = "CoffeeMindData";

    /*
     * @method load
     * @return {Object} the data as JSON object
     */
    load = function() {
      var data, match, re;
      re = new RegExp("(?:^|;)\\s?" + escape(cookieKey) + "=(.*?)(?:;|$)", "i");
      match = document.cookie.match(re);
      data = "";
      if (match) {
        data = unescape(match[1]);
      } else {
        data = "{}";
      }
      return JSON.parse(data);
    };

    /*
     * @method set
     * @param {String} key
     * @param {Object} data
     */
    set = function(key, data) {
      var db;
      db = load();
      db[key] = data;
      document.cookie = cookieKey + "=" + escape(JSON.stringify(db)) + "; path=/";
      return null;
    };

    /*
     * @method get
     * @param {String} key
     * @return {Object} the value for the key if exists, null else
     */
    get = function(key) {
      var db, value;
      db = load();
      value = db[key];
      if (value) {
        return value;
      } else {
        return null;
      }
    };
    return {
      set: set,
      get: get
    };
  })();

}).call(this);

//# sourceMappingURL=storage.cookie.js.map
