// Generated by CoffeeScript 1.8.0
(function() {
  var App;

  console.log('loading requestAnimationFrame.coffee');

  App = typeof exports !== "undefined" && exports !== null ? exports : window;

  App.requestAnimationFrame = (function() {
    return App.requestAnimationFrame || App.webkitRequestAnimationFrame || App.mozRequestAnimationFrame || App.oRequestAnimationFrame || App.msRequestAnimationFrame || function(callback, element) {
      return App.setTimeout((function() {
        return callback(Date.now());
      }), 1000 / 60);
    };
  })();

  App.cancelRequestAnimationFrame = (function() {
    return App.cancelRequestAnimationFrame || App.webkitCancelRequestAnimationFrame || App.mozCancelRequestAnimationFrame || App.oCancelRequestAnimationFrame || App.msCancelRequestAnimationFrame || window.clearTimeout;
  })();

}).call(this);

//# sourceMappingURL=requestAnimationFrame.js.map
